#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1alpha1
kind: SCMPoll
metadata:
  name: docker-operator-main-poll
  namespace: galasa-tekton
spec:
  metadata:
    name: docker-operator-main-poll
  description: Polls for docker operator changes to the main branch
  pollFrequency: 60
  tidy: true
  concurrentPipelines: false
  repositories:
    - name: galasa-docker-operator
      type: github-head
      serviceAccountName: poll-sa
      params:
      - name: url
        value: https://api.github.com/repos/galasa-dev/galasa-docker-operator
      - name: branch
        value: main
      - name: rebuildString
        value: "rebuild"
  pipelineRunSpec:
    params:
    - name: distBranch
      value: main
    - name: refspec
      value: +refs/heads/main:refs/heads/main
    - name: imageName
      value: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-docker-operator-amd64:main
    - name: noPush
      value: ""
    pipelineRef:
      name: docker-operator-build
    serviceAccountName: build-bot
    podTemplate:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
    workspaces:
    - name: git-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-temp
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi