#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-operator-task
  namespace: galasa-tekton
spec:
  workspaces:
  - name: git-workspace
    optional: false
    mountpath: /workspace/git
  params:
  - name: imageName
    type: string
  - name: distBranch
    type: string
  - name: dockerBuildRepo
    type: string
    default: harbor-cicsk8s.hursley.ibm.com
  - name: noPush
    type: string
    default: ""
  steps:
  - name: gradle-build 
    image: $(params.dockerBuildRepo)/galasadev/galasa-build
    command:
          - gradle
          - '--no-daemon'
          - '--console'
          - plain
          - build
    workingDir: /workspace/git/galasa-docker-operator/
  - name: docker-build
    workingDir: /workspace/git/galasa-docker-operator/
    image: $(params.dockerBuildRepo)/common/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git/galasa-docker-operator
    - --destination=$(params.imageName)
    - --oci-layout-path=/workspace/git/galasa-docker-operator/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - $(params.noPush)
    - --build-arg=dockerRepository=$(params.dockerBuildRepo)